---
alias: [Forbearance]
created: 2021-03-02T20:01:18 (UTC +11:00)
tags: [Forbearance Definition, Forbearance]
source: https://www.investopedia.com/terms/f/forbearance.asp
author: Julia Kagan
---

# Forbearance Definition

> ## Excerpt
> Forbearance is a form of repayment relief involving temporary postponement of loan payments, usually used to skirt legal action and loss of repayment.

---

Forbearance
## What Is Forbearance?

Forbearance is a temporary postponement of mortgage payments. It is a form of repayment relief granted by the lender or creditor in lieu of forcing a property into foreclosure. Loan owners and loan insurers may be willing to negotiate forbearance options because the losses generated by property [foreclosure](https://www.investopedia.com/terms/f/foreclosure.asp) typically fall on them.

Forbearance can also occur with other types of loans, such as can be the case with student loans. As an example, the U.S. Congress passed the [Coronavirus Aid, Relief, and Economic Security Act (CARES Act)](https://www.investopedia.com/coronavirus-aid-relief-and-economic-security-cares-act-4800707) in 2020 to address the economic fallout from COVID-19. The package included provisions for student loan forbearance. Some state governments have also enacted their own regulations related to forbearance amid the pandemic

### Key Takeaways

-   Forbearance is a temporary postponement of mortgage payments granted by the lender or creditor in lieu of forcing a property into foreclosure.
-   The terms of a forbearance agreement are negotiated between the borrower and the lender.
-   The borrower must demonstrate the cause for repayment postponement, such as financial difficulties associated with a major illness or the loss of a job.
-   Borrowers of mortgage loans backed by government programs, including Fannie Mae and Freddie Mac, can get financial relief if they're affected by COVID-19.

## Understanding Forbearance

Forbearance provides the borrower time to repay [delinquent mortgage](https://www.investopedia.com/terms/d/delinquent_mortgage.asp) sums. This is advantageous to the struggling borrower, but offering forbearance also benefits the loan owner, such as a bank, which frequently loses money on foreclosure after paying the fees associated with the process. However, loan servicers, which collect payments but do not own the loans, may be less willing to work with borrowers on forbearance relief because they do not bear as much [financial risk](https://www.investopedia.com/terms/f/financialrisk.asp).

### Forbearance Terms

The terms of a forbearance agreement are negotiated between the borrower and the lender. The opportunity for such an agreement depends on the likelihood that the borrower will be able to resume monthly mortgage repayments once the temporary forbearance is over. The lender may approve a full reduction of the borrower's payment or only a partial one, depending upon the extent of the borrower's need and the lender's confidence in the borrower's ability to catch up at a later date.

In some cases, the lender grants the borrower a full [moratorium](https://www.investopedia.com/terms/m/moratorium.asp) on making mortgage payments for the forbearance period. Other times, the borrower is required to make interest payments but not pay down the [principal](https://www.investopedia.com/terms/p/principal.asp). In still other cases, the borrower pays only part of the interest with the unpaid portion resulting in negative [amortization](https://www.investopedia.com/terms/a/amortization.asp). Another forbearance option is for the lender to reduce the borrower's interest rate on a temporary basis.

### Will You Receive Forbearance?

Being awarded forbearance on a mortgage requires contacting the lender, explaining the situation, and receiving approval. Borrowers with a history of making payments on time are more likely to be granted this option. The borrower must also demonstrate the cause for repayment postponement, such as financial difficulties associated with a major illness or the loss of a job.

A borrower who worked the same job for 10 years and never missed a mortgage payment during that time, for example, is a good candidate to receive forbearance following a layoff, particularly if the borrower has in-demand skills and is likely to land a comparable job within weeks or months. Conversely, a lender is less likely to grant forbearance to a laid-off borrower with a spotty employment history or a track record of missing mortgage payments.

## Special Considerations

Forbearance assistance is now being offered to mortgage borrowers affected by COVID-19, the illness caused by the novel coronavirus. The moratorium on foreclosures and evictions was due to expire on Jan. 31, 2021, but was extended.1However, the extension date varies, depending on the government agency or mortgage loan program.

### Fannie Mae and Freddie Mac

[Fannie Mae](https://www.investopedia.com/mortgage/fannie-mae-loans/) and [Freddie Mac](https://www.investopedia.com/terms/f/freddiemac.asp) are offering assistance for affected homeowners with mortgage loans backed by these enterprises. Fannie Mae and Freddie Mac have extended the foreclosure moratoriums on single-family foreclosures and [real estate owned](https://www.investopedia.com/terms/r/realestateowned.asp) (REO) evictions until Mar. 31, 2021, as outlined by the [Federal Housing Finance Agency (FHFA)](https://www.investopedia.com/terms/f/fhfa.asp). REO properties are bank-owned properties seized due to nonpayment.2

Here are the Fannie Mae guidelines for single-family mortgages:

-   Homeowners who are adversely impacted by this national emergency may request mortgage assistance by contacting their mortgage servicer.
-   Homeowners impacted by this national emergency are eligible for a forbearance plan to reduce or suspend their mortgage payments for up to 12 months.
-   Credit bureau reporting of past-due payments of borrowers in a forbearance plan as a result of hardships attributable to this national emergency is suspended.
-   Homeowners in a forbearance plan will not incur late fees.
-   After forbearance, a servicer must work with the borrower on a permanent plan to help maintain or reduce monthly payment amounts as necessary, including a loan modification33

Homeowners can find out if they have a [mortgage that is owned by Fannie Mae](https://www.knowyouroptions.com/loanlookup) or call Fannie Mae at 1-800-232-6643 for more information.

Freddie Mac also took similar actions to protect single-family homeowners with Freddie Mac-owned mortgages who are affected by COVID-19. Relief includes:4

-   Ensuring payment relief by providing borrowers forbearance for up to 12 months.
-   Waiving assessments of penalties or late fees against borrowers.
-   Suspending the reporting of delinquency related to forbearance, repayment, or trial plans to credit bureaus.
-   Allowing servicers to offer borrowers additional loss mitigation options that are typically only enacted to address natural disasters. This includes loan modifications that give servicers options to provide payment relief or keep the payment the same after the forbearance period.5

Visit [MyHomebyFreddieMac](https://myhome.freddiemac.com/mortgage-help/contact.html) for more information and a mortgage look-up tool.

### Other Mortgage Relief Programs

Some mortgage loans in rural areas are guaranteed by the [U.S. Department of Agriculture (USDA)](https://www.investopedia.com/terms/u/usda.asp). The foreclosure moratorium for the USDA Single Family Housing Direct and Guaranteed loan program was extended until June 30, 2021.1

Mortgage loans that are backed by the U.S. [Department of Housing and Urban Development (HUD)](https://www.investopedia.com/terms/u/us-department-housing-urban-development-hud.asp) and insured by the [Federal Housing Administration (FHA)](https://www.investopedia.com/terms/f/fhaloan.asp) or guaranteed by the Office of Native American Programs’ (Section 184 and 184 A loan guarantee programs) were also extended through June 30, 2021.6

Also, the eviction and foreclosure moratorium for VA loans from the Department of Veteran Affairs has been pushed out until June 30, 2021. The Department of Housing and Urban Development, Department of Veterans Affairs, and Department of Agriculture also extended the date for when borrowers can apply for forbearance—allowing the enrollment window to continue until June 30, 2021.1
