---
alias: [Sukuk]
created: 2021-03-02T23:47:47 (UTC +11:00)
tags: [Sukuk Definition, Sukuk Definition]
source: https://www.investopedia.com/terms/s/sukuk.asp
author: Akhilesh Ganti
---

# Sukuk Definition

> ## Excerpt
> A sukuk is a bond-like financial product that complies with Islamic finance (sharia) rules.

---

Sukuk Definition
## What Is a Sukuk?

A _sukuk_ is an Islamic financial certificate, similar to a bond in Western finance, that complies with Islamic religious law commonly known as [Sharia](https://www.investopedia.com/terms/s/shariah.asp). Since the traditional Western interest-paying bond structure is not permissible, the issuer of a sukuk essentially sells an investor group a certificate, and then uses the proceeds to purchase an asset that the investor group has direct partial ownership interest in. The issuer must also make a contractual promise to buy back the bond at a future date [at par](https://www.investopedia.com/terms/a/at-par.asp) value.

### Key Takeaways

-   A sukuk is a sharia-compliant bond-like instruments used in Islamic finance.
-   Sukuk involves a direct asset ownership interest, while bonds are indirect interest-bearing debt obligations.
-   Both sukuk and bonds provide investors with payment streams, however income derived from a sukuk cannot be speculative that would make it no longer _halal._

## Understanding Sukuk

With the rise of [Islamic finance](https://www.investopedia.com/terms/i/islamicbanking.asp), sukuk have become extremely popular since 2000, when the first such products were issued in Malaysia. Bahrain followed suit in 2001. Fast forward to current times, and sukuk are used by Islamic corporations and state-run organizations alike around the globe, taking up an increasing share of the global fixed-income market.

Islamic law prohibits what's known as "[riba](https://www.investopedia.com/terms/r/riba.asp)," or what we understand as "[interest](https://www.investopedia.com/terms/i/interestrate.asp)" in the West. Therefore, traditional, Western debt instruments cannot be used as viable investment vehicles or ways to raise capital for a business. To circumvent this, sukuk were created in order to link the returns and cash flows of debt financing to a specific asset being purchased, effectively distributing the benefits of that asset. This allows investors to work around the prohibition outlined under Sharia and still receive the benefits of debt financing. However, because of the way that sukuk are structured, financing can only be raised for [identifiable assets](https://www.investopedia.com/terms/i/identifiable_asset.asp).

Thus, sukuk represent aggregate and undivided shares of ownership in a tangible asset as it relates to a specific project or a specific investment activity. An investor in a sukuk, therefore, does not own a debt obligation owed by the bond issuer, but instead owns a piece of the asset that's linked to the investment. This means that sukuk holders, unlike bond holders, receive a portion of the earnings generated by the associated asset.

## Sukuk vs. Traditional Bonds

Sukuk and conventional bonds do share similar characteristics, but also have important key differences:

Similarities

-   Both provide investors with payment streams.
    
-   Bonds and sukuk are issued to investors and may be used to raise capital for a firm.
    
-   Both are considered to be safer investments than equities.
    
-   Sukuk investors receive profit generated by the underlying asset on a periodic basis while bond investors receive periodic interest payments.
    

Key Differences

-   Sukuk involves asset ownership while bonds are debt obligations.
    
-   If the asset backing a sukuk appreciates then the sukuk can appreciate whereas bond yield is strictly due to its interest rate.
    
-   Assets that back sukuk are _halal_ whereas bonds are often riba and may finance non sharia compliant businesses or fuel speculation.
    
-   Sukuk valuation is based on the value of the assets backing them while a bonds price is largely determined by its credit rating.
    

## Sukuk Example: Trust Certificates

The most common type of a sukuk comes in the form of a [trust certificate](https://www.investopedia.com/terms/t/trust-certificate.asp). These certificates are also governed by Western law, however, the structure of this type of sukuk is more nuanced. The organization raising funds first creates an offshore [special purpose vehicle](https://www.investopedia.com/terms/s/spv.asp) (SPV). The SPV then issues trust certificates to qualified investors and puts the proceeds of the investments toward a funding agreement with the issuing organization. In return, the investors earn a portion of the profits linked to the asset.

Sukuk structured as trust certificates are only applicable if the SPV can be created in an offshore jurisdiction that allows such trusts. This is sometimes not possible. If an SPV and trust certificates can't be created, a sukuk can be structured as an alternative civil-law structure. In this scenario, an asset-leasing company is created in the country of origin, effectively purchasing the asset and leasing it back to the organization in need of financing.
