---
alias: [Taxation]
created: 2021-03-02T23:56:25 (UTC +11:00)
tags: [Taxation Definition, Taxation]
source: https://www.investopedia.com/terms/t/taxation.asp
author: Julia Kagan
---

# Taxation Definition

> ## Excerpt
> Taxation refers to the act of levying or imposing a tax by a taxing authority. Taxes include income, capital gains, or estate.

---

Taxation
## What Is Taxation?

Taxation is a term for when a taxing authority, usually a government, levies or imposes a financial obligation on its citizens or residents. Paying taxes to governments or officials has been a mainstay of civilization since ancient times.

The term "taxation" applies to all types of involuntary levies, from income to capital gains to [estate taxes](https://www.investopedia.com/terms/e/estatetax.asp). Though taxation can be a noun or verb, it is usually referred to as an act; the resulting revenue is usually called "taxes."

### Key Takeaways

-   Taxation occurs when a government or other authority requires that a fee be paid by citizens and corporations, to that authority.
-   The fee is involuntary, and as opposed to other payments, not linked to any specific services that have been or will be provided.
-   Tax occurs on physical assets, including property and transactions, such as a sale of stock, or a home. 
-   Types of taxes include income, corporate, capital gains, property, inheritance, and sales.

## Understanding Taxation

Taxation is differentiated from other forms of payment, such as market exchanges, in that taxation does not require consent and is not directly tied to any services rendered. The government compels taxation through an implicit or explicit threat of force. Taxation is legally different than extortion or a protection [racket](https://www.investopedia.com/terms/r/racketeering.asp) because the imposing institution is a government, not private actors.

Tax systems have varied considerably across jurisdictions and time. In most modern systems, taxation occurs on both physical [assets](https://www.investopedia.com/terms/a/asset.asp), such as property and specific events, such as a sales transaction. The formulation of tax policies is one of the most critical and contentious issues in modern politics.

## Taxation in the United States

The U.S. government was originally funded on very little direct taxation. Instead, federal agencies assessed [user fees](https://www.investopedia.com/terms/u/user-fee.asp) for ports and other government property. In times of need, the government would decide to sell government assets and [bonds](https://www.investopedia.com/terms/b/bond.asp) or issue an assessment to the states for services rendered. In fact, Thomas Jefferson abolished direct taxation in 1802 after winning the presidency; only [excise taxes](https://www.investopedia.com/terms/e/excisetax.asp) remained, which Congress repealed in 1817. Between 1817 and 1861, the federal government collected no internal revenue.

An income tax of 3% was levied on high-income earners during the Civil War. It was not until the Sixteenth Amendment was ratified in 1913 that the federal government assessed taxes on income as a regular revenue item. As of 2020, U.S. taxation applies to a wide range of items or activities, from income to cigarette and gasoline purchases to inheritances and when winning at a casino or even Nobel Prize.

In 2012, as part of ruling on the Affordable Care Act (ACA), the U.S. Supreme Court ruled that failure to purchase specific goods or services, such as [health insurance](https://www.investopedia.com/terms/h/healthinsurance.asp), was considered a tax and not a fine.

## Purposes and Justifications for Taxation

The most basic function of taxation is to fund government expenditures. Varying justifications and explanations for taxes have been offered throughout history. Early taxes were used to support the ruling classes, raise armies, and build defenses. Often, the authority to tax stemmed from divine or supranational rights.

Later justifications have been offered across utilitarian, economic, or moral considerations. Proponents of [progressive levels of taxation](https://www.investopedia.com/terms/p/progressivetax.asp) on high-income earners argue that taxes encourage a more equitable society. Higher taxes on specific products and services, such as tobacco or gasoline, have been justified as a deterrent to consumption. Advocates of public goods theory argue taxes may be necessary in cases in which the private provision of public goods is considered sub-optimal, such as with lighthouses or national defense.

## Different Types of Taxation

As mentioned above, taxation applies to all different types of levies. These can include (but are not limited to): 

-   **Income tax**: Governments impose income taxes on financial income generated by all entities within their jurisdiction, including individuals and businesses.
-   **Corporate tax**: This type of tax is imposed on the profit of a business.
-   **Capital gains**: A tax on capital gains is imposed on any capital gains or profits made by people or businesses from the sale of certain assets including stocks, bonds, or real estate. 
-   **Property tax**: A property tax is asses by a local government and paid for by the owner of a property. This tax is calculated based on property and land values. 
-   **Inheritance**: A type of tax levied on individuals who inherit the estate of a deceased person. 
-   **Sales tax**: A consumption tax imposed by a government on the sale of goods and services. This can take the form of a value-added tax (VAT), a goods and services tax (GST), a state or provincial sales tax, or an excise tax.
