---
alias: [Underwriting Income]
created: 2021-03-03T00:17:17 (UTC +11:00)
tags: [Underwriting Income Definition, Underwriting Income]
source: https://www.investopedia.com/terms/u/underwriting-income.asp
author: Julia Kagan
---

# Underwriting Income Definition

> ## Excerpt
> Underwriting income is profit generated by an insurer's underwriting activity. It is the difference between premiums collected and claims paid out.

---

Underwriting Income
## What Is Underwriting Income?

Underwriting income is the profit generated by an insurer's [underwriting](https://www.investopedia.com/terms/u/underwriting.asp) activity over a period of time. Underwriting income is the difference between [premiums](https://www.investopedia.com/terms/p/premium.asp) collected on insurance policies by the insurer and expenses incurred and claims paid out. Huge claims and disproportionate expenses may result in an underwriting loss, rather than income, for the insurer. The level of underwriting income is an accurate measure of the efficiency of an insurer's underwriting activities.

### Key Takeaways

-   Underwriting income is the profit generated by an insurance company through its course of business.
-   The difference between premiums collected on insurance policies and business expenses plus claims paid out is the underwriting income.
-   Underwriting income can be an indicator of how much new business an insurance company is bringing in or how well its risk analysis process is in predicting the number of insurance claims needing to be paid out.
-   If an insurance company can generate positive underwriting income, it is in a better financial place and will not have to rely on investment income or writing riskier policies.

## Understanding Underwriting Income

When an [insurance](https://www.investopedia.com/terms/i/insurance.asp) company writes an insurance policy for a new client or renews a policy for an existing client, they receive an insurance premium as payment. This is their revenue. The costs associated with an insurance company are the ordinary business costs as well as money paid out to clients when they file an [insurance claim](https://www.investopedia.com/terms/i/insurance_claim.asp) for an accident or other such event. The difference between revenue and costs, like any business, is the income, in this case, the underwriting income.

An insurer's underwriting income may fluctuate from quarter to quarter, with [natural and other disasters](https://www.investopedia.com/financial-edge/0311/the-financial-effects-of-a-natural-disaster.aspx) such as earthquakes, hurricanes, and fires leading to huge underwriting losses. Hurricane Katrina, the largest natural catastrophe in U.S. history, caused an underwriting loss of $2.8 billion for the U.S. property/casualty insurance industry in the first nine months of 2005, compared with underwriting income of $3.4 billion in the corresponding period of 2004.

Withstanding extreme events, such as earthquakes and hurricanes, underwriting income is an indicator of how well an insurance company is performing. If the underwriting income is consistently negative, the insurance company could not be bringing in enough new business (underwriting new policies) to generate more revenue.

Conversely, it can also indicate that the policies that it is writing are risky, resulting in claims being paid out often. This might shed light on the fact that the [risk](https://www.investopedia.com/terms/u/underwriting-risk.asp) analysis an insurance company is performing on a business or individual when underwriting a policy is not accurate.

It's important for an insurance company to find a balance because if it is constantly paying out claims more than it is bringing in through underwriting revenue, this could lead to the inability to pay out future claims or [insolvency](https://www.investopedia.com/terms/i/insolvency.asp).

## Underwriting Income vs. Investment Income

Underwriting income is calculated as the difference between an insurance company's earned premiums and its expenses and claims. For example, if an insurer collects $50 million in [insurance premiums](https://www.investopedia.com/terms/i/insurance-premium.asp) over a year, and spends $40 million in insurance claims and associated expenses, its underwriting income is $10 million.

[Investment income](https://www.investopedia.com/terms/i/investmentincome.asp), meanwhile, comes from [capital gains](https://www.investopedia.com/terms/c/capitalgain.asp), [dividends](https://www.investopedia.com/terms/d/dividend.asp), and other investments related to the purchase and sale of securities.  

It's important when analyzing an insurance company, including the company's management, that they not look at overall income or profits, but also focus on underwriting income, to determine how well the business is performing through its [core](https://www.investopedia.com/terms/c/coreearnings.asp) operations.

## Underwriting Income and the Underwriting Cycle

The [underwriting cycle](https://www.investopedia.com/terms/u/underwriting-cycle.asp) is the periodic rise and fall of the insurance industry's underwriting income. The sources of this cycle aren't completely clear; however, since the swings in investment income are mild, fluctuations in underwriting income drive this cyclical rise and fall.

The number of insurance company insolvencies is proportional to the fall of underwriting income. Large drops in underwriting income can indicate that the underlying insurance policies are under-priced in the market or that the insurance companies are writing riskier policies, resulting in losses.

Insurance companies with solidly performing underwriting income are generally stronger financially because they don't have to make up for poor performance by increasing their risks on the investment side of the business or by underwriting riskier policies.
