---
alias: [Roll Yield Defined]
created: 2021-03-02T23:27:49 (UTC +11:00)
tags: [Roll Yield Defined, What Is a Roll Yield]
source: https://www.investopedia.com/terms/r/roll-yield.asp
author: James Chen
---

# Roll Yield Defined

> ## Excerpt
> Roll yield is the return generated by rolling a short-term futures contract into a longer-term one when the futures market is in backwardation.

---

What Is a Roll Yield
## What Is Roll Yield?

Roll yield is the amount of return generated in the futures market after an investor rolls a short-term contract into a longer-term contract and profits from the [convergence](https://www.investopedia.com/terms/c/convergence.asp) of the futures price toward a higher spot or cash price. Roll yield is positive when a futures market is in [backwardation](https://www.investopedia.com/terms/b/backwardation.asp), which occurs when a futures contract trades at a higher price as it approaches expiration, compared to when the contract is further away from expiration.

## Understanding Roll Yield

Roll yield is a profit that can be generated when investing in the futures market due to the price difference between futures contracts with different [expiration dates](https://www.investopedia.com/terms/e/expirationdate.asp). When investors purchase futures, they have both the right and the obligation to buy the asset underlying the futures investment at a specified date in the future, unless they sell their position (to offset the long futures position) ahead of the [delivery date](https://www.investopedia.com/terms/d/deliverydate.asp).

### Key Takeaways

-   Roll yield is the return from adjusting a futures position from one futures contract to a longer-dated contract.
-   Positive roll yield exists when a futures market is in backwardation, which occurs when the short-term contracts trade at a premium to longer-dated contracts.
-   When the market is in contango, the longer-term contracts are more expensive than short-term contracts and roll yield will be negative.

Most futures investors do not want to take delivery of the physical asset that the futures investment represents, so they close the position before expiration or roll their near-term expiring futures investments into other [futures contracts](https://www.investopedia.com/terms/f/futurescontract.asp) with expiration dates further in the future. Rolling the position allows the investor to maintain their investments in the assets without having to take physical delivery.

## Backwardation vs. Contango

When the market is in backwardation, the future price of an asset is below the expected cash or [spot price](https://www.investopedia.com/terms/s/spotprice.asp). In this case, an investor profits when the position is rolled to the contract with a later expiration date because the investor is effectively paying less money than expected by the spot market for the underlying asset that the futures investment represents.

For example, imagine that an investor holds 100 [crude oil](https://www.investopedia.com/terms/c/crude-oil.asp) contracts and wants to buy 100 again for expiration at a later date. If the contract's future price is below the spot price, the investor is actually rolling into the same quantity of an asset for a lower price.

Negative roll yield occurs when a market is in [contango](https://www.investopedia.com/terms/c/contango.asp), which is the opposite of backwardation. When a market is in contango, the future price of the asset is above the expected future spot price, and so the investor will lose money when rolling contracts.

Returning to the example of an investor with 100 oil contracts, if the investor wants to roll into 100 oil contracts with a later expiration date as the contract nears expiration, the investor will pay more money for the oil contracts compared to the spot market. They would, therefore, have to pay more money to maintain the same number of contracts. Negative roll yields have sometimes led to significant losses by hedge funds and [exchange traded funds that hold futures](https://www.investopedia.com/terms/c/commodity-etf.asp).
