---
alias: [Worldwide Income]
created: 2021-03-03T01:03:36 (UTC +11:00)
tags: [Worldwide Income Definition, Worldwide Income]
source: https://www.investopedia.com/terms/w/worldwide-income.asp
author: Will Kenton
---

# Worldwide Income Definition

> ## Excerpt
> Worldwide income is an aggregation of a taxpayer's domestic and foreign income. In the U.S., citizens and resident aliens are subject to tax on worldwide income.

---

Worldwide Income
## What Is Worldwide Income?

In the United States, worldwide income describes an [aggregation](https://www.investopedia.com/terms/a/aggregation.asp) of a taxpayer's domestic and foreign income. Worldwide income is income earned anywhere in the world and is used to determine taxable income. In the U.S., citizens and resident aliens are subject to tax on worldwide income.1

## Understanding Worldwide Income

The [IRS](https://www.investopedia.com/terms/i/irs.asp) demands to know about all of a taxpayer's worldwide income, taxable or otherwise. 1 Money that is paid to U.S. citizens or resident aliens as wages, independent contractor payments or unearned income from pensions, rents, royalties, and investments may all be subject to tax by the IRS.2 There are some exceptions for [U.S. taxpayers who live abroad](https://www.investopedia.com/financial-edge/0412/how-to-pay-taxes-if-youre-overseas.aspx).3

## Measuring Worldwide Income

The most comprehensive measure of worldwide income includes a total aggregation of revenue generated by a tax-paying entity from all sources that includes foreign, domestic, passive, and [active income](https://www.investopedia.com/terms/a/activeincome.asp) from operations and investments. Each source of revenue must be reported to the IRS for tax purposes.1 4 The IRS can allow an exclusion or tax credit for a certain portion of earnings generated by U.S. citizens who've worked abroad. This exclusion or credit may take effect to avoid the problem of [double taxation](https://www.investopedia.com/terms/d/double_taxation.asp)—which would arise if a taxpayer has already paid taxes to another jurisdiction (not the U.S.).5 6

Multinational corporations and wealthy individuals usually take advantage of international tax specialists, a specialty among both lawyers and accountants, to decrease or otherwise shelter their worldwide tax liabilities. These tax strategies can delay tax payments, which can lead to compound growth and material increases in capital bases.

With any system of taxation, creative tax advisors can shift or [recharacterize](https://www.investopedia.com/terms/r/recharacterization.asp) income in a manner that reduces taxation. In turn, many jurisdictions often impose rules relating to shifting income among commonly controlled parties, often referred to as transfer pricing rules. Residency-based systems are subject to taxpayer attempts to defer recognition of income through the use of related parties. A few jurisdictions impose rules limiting such deferral. Agreements among governments (treaties) often attempt to reconcile who should be entitled to tax what. Most of these tax treaties offer at minimum a base mechanism for resolution of disputes between parties.
