---
alias: [Yen ETF]
created: 2021-03-03T01:08:28 (UTC +11:00)
tags: [Yen ETF Definition, Yen ETF Definition]
source: https://www.investopedia.com/terms/y/yen-etf.asp
author: Daniel Liberto
---

# Yen ETF Definition

> ## Excerpt
> A yen ETF is an exchange-traded fund (ETF) that tracks the Japanese yen (JPY) in the FX markets.

---

Yen ETF Definition
## What Is a Yen ETF?

A yen ETF is an [exchange traded fund](https://www.investopedia.com/terms/e/etf.asp) (ETF) that tracks the relative value of Japan’s currency, the Japanese yen ([JPY](https://www.investopedia.com/terms/forex/j/jpy-japanese-yen.asp)), in the foreign exchange ([forex](https://www.investopedia.com/terms/forex/f/foreign-exchange-markets.asp)) market against a [basket](https://www.investopedia.com/terms/c/currencybasket.asp) of other currencies or a single currency such as the U.S. dollar ([USD](https://www.investopedia.com/terms/u/usd.asp)). This is achieved by investing primarily in yen-backed assets, including short-term debt instruments and bonds, or simply holding the spot currency in interest-bearing accounts.

### Key Takeaways

-   A yen ETF is tasked with tracking the relative value of Japan’s currency against a basket of other currencies or a single currency.
-   This is achieved by investing in instruments such as futures contracts, debt securities, money market funds, and cash deposits, all primarily held in yen.
-   Some yen ETFs match the current income earned on the yen assets with a dividend yield. Others use that income to pay the expenses of managing the ETF.
-   Historically, the yen has been considered a safe haven, meaning it is sought after by investors in times of heightened geopolitical risk.

## How Yen ETFs Work

Not too long ago, buying and selling foreign currencies was a privilege generally reserved for experienced traders with expert knowledge. ETFs helped to change that, making the forex market more accessible to the average investor.

[Currency ETFs](https://www.investopedia.com/terms/c/currency-etf.asp) are a type of pre-packaged investment tasked with tracking a certain currency, similar to how regular ETFs seek to replicate the performance of an index. These vehicles trade on a [stock exchange](https://www.investopedia.com/terms/s/stockmarket.asp). Like stocks, their prices fluctuate throughout the day as traders buy and sell them.

The portfolios of yen ETFs usually include yen-denominated [futures contracts](https://www.investopedia.com/terms/f/futurescontract.asp), [debt securities](https://www.investopedia.com/terms/d/debtsecurity.asp), money market funds, and cash deposits. These funds generate income for investors through the performance of the yen against other currencies as well as through interest generated by some securities in the portfolio. Some yen ETFs match the current [income](https://www.investopedia.com/terms/i/income.asp) earned on the yen assets with a [dividend yield](https://www.investopedia.com/terms/d/dividendyield.asp). Others use that income to pay the expenses of managing the ETF.

## Benefits of Yen ETFs

Holding investment in foreign currencies enables investors to protect themselves in case their own currency declines in value. Over the years, many have opted for the yen: the third-most widely traded currency globally, behind the [USD](https://www.investopedia.com/terms/forex/u/usd-united-states-dollar.asp) and the [euro](https://www.investopedia.com/terms/e/euro.asp), and the most widely traded currency in Asia.

The yen is sometimes used to provide diversification, as it frequently trades inversely to the other major currencies in relation to the U.S. dollar. Historically, the currency, which is often used as a [reserve currency](https://www.investopedia.com/terms/r/reservecurrency.asp) in international transactions, has even developed a reputation as a [safe haven](https://www.investopedia.com/terms/s/safe-haven.asp).

Japan is the world’s largest [creditor](https://www.investopedia.com/terms/c/creditor.asp). There’s also a popular belief among traders that investors there tend to dump foreign holdings and bring their money back home in times of hardship, bolstering demand for the yen and, subsequently, its valuation.

The Japanese yen has customarily been a popular [carry trade](https://www.investopedia.com/carry-trade-definition-4682656), too, as low-interest [rates](https://www.investopedia.com/terms/i/interestrate.asp) make it cheap to borrow to fund risk-taking in other, higher-interest currencies.

## Limitations of Yen ETFs

Some investors consider currency ETFs risky, since [macroeconomic](https://www.investopedia.com/terms/m/macroeconomics.asp) events affect currency values around the world, even in stable nations such as Japan. Unpredictable natural disasters can also have a big impact, an example being the Fukushima disaster in 2011, which caused a surge in the value of the yen, followed by a [recession.](https://www.investopedia.com/terms/r/recession.asp)

Lately, a handful of analysts have even questioned the Japanese yen’s safe-haven status, pointing to its [trade deficits](https://www.investopedia.com/terms/t/trade_deficit.asp), local [asset managers](https://www.investopedia.com/terms/a/assetmanagement.asp) buying higher-yielding foreign assets, and Japanese companies running out of decent options to deploy capital at home. The yen has also lost some of its luster as a popular carry trade as low-interest rates become commonplace among major economies.

These observations serve as a reminder that forex trading is not a market for the unprepared. Traders must be knowledgeable about major foreign currencies and stay abreast of not only the current economic stats for a country but also the underpinnings of the respective economies and the special factors that can influence the currencies, such as [commodity](https://www.investopedia.com/terms/c/commodity.asp) movement or interest rate changes.

## Yen ETF Requirements

Investors should keep tabs on all major economic data, including the release of [gross domestic product](https://www.investopedia.com/terms/g/gdp.asp) (GDP), retail sales, industrial production, inflation, [trade balances](https://www.investopedia.com/terms/b/bot.asp), employment figures, interest rates, including scheduled meetings of the central bank, and the daily news flow, when investing in currencies.

Most of the movement in currency markets is dictated by interest rates, global economic conditions, and political stabilities.

In the case of Japan and yen traders, the [Tankan survey](https://www.investopedia.com/terms/t/tankan.asp) is particularly worth paying attention to. Tankan, an economic survey of Japanese businesses, is published by the Bank of Japan (BOJ) every quarter. It is used to formulate [monetary policy](https://www.investopedia.com/terms/m/monetarypolicy.asp) and, as a result, often moves trading in Japanese stock and currency.

## Examples of Yen ETFs

The most popular yen ETF is the CurrencyShares Japanese Yen Trust (FXY) with $201 million in [assets under management](https://www.investopedia.com/terms/a/aum.asp) (AUM). FXY was first launched in 2007 by RydexSGI and seeks to mirror the price and performance of the Japanese yen relative to the USD by holding Japanese yen on deposit. The fund has an [expense ratio](https://www.investopedia.com/terms/e/expenseratio.asp) of 0.40 percent.

Investors looking to add yen ETFs to their [portfolios](https://www.investopedia.com/terms/p/portfolio.asp) have a number of other options, too. Alternatives include the ProShares Ultra Yen ETF (YCL), ProShares UltraShort Yen ETF (YCS), and VelocityShares Daily 4x Long USD vs JPY ETN (DJPY).
