---
alias: [Funds From Operations, FFO]
created: 2021-03-02T20:10:14 (UTC +11:00)
tags: [Funds From Operations (FFO), Funds From Operations (FFO)]
source: https://www.investopedia.com/terms/f/fundsfromoperation.asp
author: James Chen
---

# Funds From Operations (FFO)

> ## Excerpt
> Funds from operations, or FFO, refers to the figure used by real estate investment trusts (REITs) to define the cash flow from their operations.

---

Funds From Operations (FFO)
## What Is Funds From Operations (FFO)?

Funds from operations (FFO) refers to the figure used by real estate investment trusts ([REITs](https://www.investopedia.com/terms/r/reit.asp)) to define the cash flow from their operations. Real estate companies use FFO as a measurement of operating performance.

FFO is calculated by adding [depreciation](https://www.investopedia.com/terms/d/depreciation.asp), [amortization](https://www.investopedia.com/terms/a/amortization.asp), and losses on sales of assets to earnings and then subtracting any gains on sales of assets and any interest income. It is sometimes quoted on a per-share basis. The [FFO-per-share](https://www.investopedia.com/terms/f/funds-from-operations-per-share.asp) ratio should be used in lieu of earnings per share ([EPS](https://www.investopedia.com/terms/e/eps.asp)) when evaluating REITs and other similar investment trusts.

### Key Takeaways

-   Funds from operations (FFO) refers to the figure used by real estate investment trusts (REITs) to define the cash flow from their operations.
-   Real estate companies use FFO as a measurement of operating performance.
-   FFO excludes one-time cash inflows such as income from the sale of an asset; instead, it only includes income from business activities.

#### Funds from Operations (FFO)

## Formula and Calculation of Funds From Operations

Below is the formula for calculating funds from operations (FFO).

The formula for FFO is:

> FFO = (Net Income + Depreciation + Amortization + Losses on Property Sales) - Gains on Sales of Property - Interest Income

Below are the steps to calculate FFO:

All components of the FFO calculation are listed on a REIT's [income statement](https://www.investopedia.com/terms/i/incomestatement.asp).

1.  Obtain the figure for net income, which is the company's profit and is located at the bottom of the income statement.
2.  Depreciation and amortization are the expensed portions of a company's [tangible](https://www.investopedia.com/terms/t/tangibleasset.asp) (physical) and [intangible assets](https://www.investopedia.com/terms/i/intangibleasset.asp) for the period. Depreciation and amortization are merely accounting measures to help companies spread out the costs of their assets. The expensed amounts ultimately reduce net income for the accounting period. As a result, depreciation and amortization are added back to net income to determine the actual incoming cash or revenue from the REIT's operations.
3.  Add any losses on the sales of business property, if any. This generally includes long-term assets such as property, plant, and equipment. These losses are considered one-time and non-recurring, and are therefore not part of normal operations and should not be included in the FFO calculation.
4.  Subtract any gains or revenue earned from the sale of property from the total figure of net income, depreciation, and amortization to obtain the funds from operations for the period.
6.  Subtract any interest income the business earned. Interest income is generally not a regular part of a business's normal operations, and therefore it should not be included in the FFO calculation.

If, for example, a REIT had depreciation of $20,000, gains on sales of property of $40,000 and net profit of $100,000, its FFO would be $80,000.

In most situations, an investor would not need to calculate a REIT's FFO since all REITs are required to show their FFO calculations on their public [financial statements](https://www.investopedia.com/terms/f/financial-statements.asp). The FFO figure is typically disclosed in the [footnotes](https://www.investopedia.com/terms/f/footnote.asp) for the income statement.

## What Funds From Operations Can Tell You

FFO is a measure of the cash generated by a REIT; real estate companies use FFO as an operating performance benchmark. The National Association of Real Estate Investment Trusts ([NAREIT](https://www.investopedia.com/terms/n/nareit.asp)) originally pioneered this figure, which is a [non-GAAP](https://www.investopedia.com/terms/n/non-gaap-earnings.asp) measure.

FFO is not to be confused with a REIT's [cash flow from operations](https://www.investopedia.com/terms/c/cash-flow-from-operating-activities.asp), which is reported on the [statement of cash flows (CFS)](https://www.investopedia.com/investing/what-is-a-cash-flow-statement/). Instead, FFO measures the net amount of cash and equivalents that flows into a firm from regular, ongoing business activities. FFO should not be seen as an alternative to cash flow or as a measure of liquidity.

For example, a typical company's cash flow would be influenced by the money earned from the sale of an asset, but FFO excludes those gains. Also, a typical company would show a cash inflow on its CFS if the company received loan proceeds from a bank. However, FFO does not include such cash inflows, but instead, it is only a measure of the income from business activities.

## Why FFO Is a Good Measure of REIT Performance

FFO compensates for cost-accounting methods that may inaccurately communicate a REIT's true performance. [GAAP](https://www.investopedia.com/terms/g/gaap.asp) accounting requires that all REITs depreciate their [investment properties](https://www.investopedia.com/terms/i/investment-property.asp) over time using one of the standard depreciation methods. However, many investment properties actually increase in value over time, making depreciation inaccurate in describing the value of a REIT. Depreciation and amortization must be added back to net income to reconcile this issue.

FFO also subtracts any gains on sales of property because these types of sales are considered to be nonrecurring. REITs must pay out 90% of all [taxable income](https://www.investopedia.com/terms/t/taxableincome.asp) in the form of [dividends](https://www.investopedia.com/terms/d/dividend.asp), which are cash payments to investors. Gains on sales of property do not add to a REIT's taxable income and should therefore not be included in the measurement of value and performance.

As mentioned, FFO per share is sometimes provided by firms as a supplement to their EPS. Earnings per share is a company's net income divided by the outstanding [equity](https://www.investopedia.com/terms/e/equity.asp) shares. EPS and FFO per share provide a measure of how much income is being generated on a per-share basis. These measures also help investors determine whether the money is being used effectively by management. Also, many analysts and investors assess a REIT's price-FFO ratio as a supplement to the [price-earnings ratio](https://www.investopedia.com/terms/p/price-earningsratio.asp), which is the stock price divided by EPS. In the case of a REIT, the market price of the REIT would be divided by its FFO per share.

## Adjusted Funds From Operations

Increasingly, real estate [analysts](https://www.investopedia.com/terms/a/analyst.asp) are also calculating a REIT's adjusted funds from operations ([AFFO](https://www.investopedia.com/terms/a/affo.asp)). This calculation takes a REIT's FFO and subtracts any recurring expenditure that is [capitalized](https://www.investopedia.com/terms/c/capitalization.asp) and then amortized, as well as any [straight-lining](https://www.investopedia.com/terms/s/straightlinebasis.asp) of rents. These recurring capital expenditures may include such maintenance expenses as painting projects or roof replacements. AFFO has gained traction as a more accurate estimate of a REIT's earnings potential.

The AFFO measure was developed to provide a better measure of a REIT's cash generated or dividend-paying capacity. In addition to AFFO, this alternate measure is sometimes referred to as funds available for distribution or cash available for distribution.

## Example of How to Use Funds From Operations

Popular mall REIT Simon Property Group reported funds from operations on its 2017 income statement of $4 billion, up 6% from 2016. The firm's net income, meanwhile, totaled $2.2 billion. 

To arrive at FFO, the firm added back depreciation and amortization of about $1.8 billion, and further adjusted for other smaller figures—including a reduction of $5.3 million for payment of preferred distributions and dividends, and a [noncontrolling interests](https://www.investopedia.com/terms/n/noncontrolling_interest.asp) portion of depreciation and amortization that resulted in an additional $17.1 million reduction. Simon additionally reported a diluted FFO-per-share figure of $11.21, compared to a [diluted EPS](https://www.investopedia.com/terms/d/dilutedeps.asp) figure of $6.24.
