---
alias: [High Minus Low (HML)]
created: 2021-03-02T20:43:24 (UTC +11:00)
tags: [High Minus Low (HML) Definition, Understanding High Minus Low (HML)]
source: https://www.investopedia.com/terms/h/high_minus_low.asp
author: Jason Fernando
---

# High Minus Low (HML) Definition

> ## Excerpt
> High Minus Low (HML), also referred to as the value premium, is one of three factors used in the Fama-French three-factor model.

---

Understanding High Minus Low (HML)
## What Is High Minus Low (HML)?

High Minus Low (HML), also referred to as the value premium, is one of three factors used in the [Fama-French three-factor model](https://www.investopedia.com/terms/f/famaandfrenchthreefactormodel.asp). HML accounts for the spread in returns between value stocks and growth stocks and argues that companies with high book-to-market ratios, also known as value stocks, outperform those with lower book-to-market values, known as growth stocks.

### Key Takeaways

-   High Minus Low (HML) is a component of the Fama-French three-factor model.
-   HML refers to the outperformance of value stocks over growth stocks.
-   Along with another factor, Small Minus Big (SMB), HML is used to estimate portfolio managers’ excess returns.

## Understanding High Minus Low (HML)

To understand HML, it is important to first have a basic understanding of the Fama-French three-factor model. Founded in 1992 by Eugene Fama and Kenneth French, the Fama-French three-factor model uses three factors, one of which is HML, in order to explain the [excess returns](https://www.investopedia.com/terms/e/excessreturn.asp) in a manager’s portfolio.

The underlying concept behind the model is that the returns generated by portfolio managers are due in part to factors that are beyond the managers’ control. Specifically, [value stocks](https://www.investopedia.com/terms/v/valuestock.asp) have historically outperformed [growth stocks](https://www.investopedia.com/terms/g/growthstock.asp) on average, while smaller companies have outperformed larger ones.

Much of portfolio performance can be explained by the observed tendency of small stocks and value stocks to outperform large or growth-oriented ones on average.

The first of these factors (the outperformance of value stocks) is referred to by the term HML, whereas the second factor (the outperformance of smaller companies) is referred to by the term [Small Minus Big](https://www.investopedia.com/terms/s/small_minus_big.asp) (SMB). By determining how much of the manager's performance is attributable to these factors, the user of the model can better estimate the manager’s skill. 

In the case of the HML factor, the model shows whether a manager is relying on the value premium by investing in stocks with high [book-to-market ratios](https://www.investopedia.com/terms/b/booktomarketratio.asp) to earn an [abnormal return](https://www.investopedia.com/terms/a/abnormalreturn.asp). If the manager is buying only value stocks, the model regression shows a positive relation to the HML factor, which explains that the portfolio’s returns are attributable to the value premium. Since the model can explain more of the portfolio’s return, the original [excess return](https://www.investopedia.com/terms/e/excessreturn.asp) of the manager decreases.

## Fama and French’s Five Factor Model

In 2014, Fama and French updated their model to include five factors. Along with the original three, the new model adds the concept that companies reporting higher future earnings have higher returns in the stock market, a factor referred to as profitability. The fifth factor, referred to as investment, relates to the company’s internal investment and returns, suggesting that companies that invest aggressively in growth projects are likely to underperform in the future.
