---
alias: [VantageScore]
created: 2021-03-03T00:34:23 (UTC +11:00)
tags: [VantageScore Definition, VantageScore]
source: https://www.investopedia.com/terms/v/vantagescore.asp
author:  Julia Kagan
---

# VantageScore Definition

> ## Excerpt
> VantageScore is a consumer credit rating product similar to the FICO score. It is used by creditors to assess the risk of lending money to a potential borrower.

---

VantageScore
## What Is VantageScore?

VantageScore is a consumer [credit rating](https://www.investopedia.com/terms/c/creditrating.asp) product developed by [the top three credit bureaus, Equifax, TransUnion, and Experian](https://www.investopedia.com/personal-finance/top-three-credit-bureaus/), in 2006 as an alternative to the [FICO score](https://www.investopedia.com/terms/f/ficoscore.asp), created by the [Fair Isaac Corporation](https://www.investopedia.com/terms/f/fico-fair-isaac.asp) in 1989.12

### Key Takeaways

-   VantageScore is a consumer credit rating product that generates a score between 300 and 850. It is an alternative to the commonly used FICO score generated by the Fair Isaac Corporation.
-   VantageScore was developed by the same three credit rating agencies—Equifax, TransUnion, and Experian—that are used by FICO to develop its scores.
-   VantageScore claims to use “machine learning” techniques to generate a more accurate picture of a consumer’s credit.

## Understanding VantageScore

VantageScore 4, the most recent version, is a [credit score](https://www.investopedia.com/terms/c/credit_score.asp) calculated through an average of five weighted factors:

1.  Total credit usage, balance, and available credit
2.  Credit mix and experience
3.  Payment history
4.  New accounts opened
5.  Age of credit history3

It employs advanced algorithms and machine learning techniques that it claims makes it more accurate than a FICO score.4 Numerous other possible factors are ignored, “including race, color, religion, nationality, gender, marital status, age, salary, occupation, employer, employment history, where you live, \[and\] total assets.”5

Early versions employed a scoring range of 501 to 990 with corresponding letter grades from A to F and weighted factors differently. VantageScore 3, however, switched to the same scoring range as FICO, 300 to 850, and eliminated the letter grades, as does VantageScore 4.6

[FICO scores remain the most popular credit score](https://www.investopedia.com/fico-credit-scores-explained-5072985), employed by about 90% of all lenders.7 However, the use of VantageScore has been increasing, growing by about 20% annually since June 2015, based on studies conducted by consulting firm Oliver Wyman. The most recent study available, looking at the year from July 1, 2018, to June 30, 2019, found that approximately 12.3 billion VantageScores were used by more than 2,500 users. Credit card issuers were the most prolific users of VantageScore, followed by banks.8

The higher your VantageScore, the lower your credit risk is.

## How VantageScore Works

Both VantageScore and the FICO score operate on data stored in consumer credit files maintained by the three national credit bureaus. The models then conduct a statistical analysis on the data to predict the likelihood a consumer will default on a loan. Both VantageScore and FICO models represent the risk of a loan default in the form of three-digit scores, with higher scores indicating a lower risk.

Anyone with a VantageScore of 600 or less is considered to have poor or very poor credit. An average or fair credit rating is anywhere between 601 and 660. Between 661 and 780 is considered a good credit score, and anything over 780 is considered to be excellent.9

The components of a VantageScore are weighted as follows:3

-   Total Credit Usage, Balance, and Available Credit (Extremely Influential)
-   Credit Mix and Experience (Highly Influential)
-   Payment History (Moderately Influential)
-   New Accounts Opened (Less Influential)
-   Age of Credit History (Less Influential)

Total credit usage, balance, and available credit look at a consumer’s [credit utilization ratio](https://www.investopedia.com/terms/c/credit-utilization-rate.asp). For example, if you have a $10,000 line of credit in one month and have drawn $5,000 from that line, your ratio would be 50%.

Credit mix and experience relates to the kinds of credit you have, with a mix of [revolving credit](https://www.investopedia.com/terms/r/revolvingcredit.asp), such as credit cards, and [installment credit](https://www.investopedia.com/terms/i/installmentdebt.asp), such as a mortgage or an auto loan, being considered the best. Payment history looks at whether you have consistently paid your bills on time or not. New accounts involve how many requests for new credit you have made, and age of credit history is how long you have maintained your credit accounts.

A VantageScore synthesizes information from all three credit bureaus and is the same for each bureau, while a FICO score only uses information from one credit bureau and is specific to that bureau.

## Differences Between FICO Scores and VantageScores

There are several points of difference between FICO and VantageScore. FICO creates a single bureau-specific score for each of the three credit bureaus, using only information from that bureau. As a result, it is actually three scores, not one, and they can vary slightly, as each bureau will have different information about a consumer.

A VantageScore is a single, tri-bureau score, combining information from all three credit bureaus and used by each of them. FICO scores require a credit history of at least six months, but VantageScores can be calculated for persons with a credit history that is less than six months old, allowing it to rate approximately 40 million more people than the FICO score.3

[Hard inquiries](https://www.investopedia.com/terms/h/hard-inquiry.asp) can adversely affect credit scores, as they are a sign that the individual may be on the hook for more credit. FICO allows for a 45-day window for student loans, auto loans, and mortgage inquiries, while VantageScore has a 14-day window for all types of loans. This means that if multiple queries are made within the window, then they are treated as a single inquiry. For example, if you take out a personal loan, apply for a credit card, and sign on to a mortgage within a 14-day period, VantageScore will treat the three inquiries for your credit score as a single one. FICO, however, will treat them as three inquiries, because it provides exceptions only for certain types of loans.
