---
alias: [Production Externality Defined]
created: 2021-03-02T19:50:25 (UTC +11:00)
tags: [Production Externality Defined, What Is a Production Externality?]
source: https://www.investopedia.com/terms/e/externality-of-production.asp
author: Will Kenton
---

# Production Externality Defined

> ## Excerpt
> Production externality refers to a side effect from an industrial operation, such as a paper mill producing waste that is dumped into a river.

---

What Is a Production Externality?
## What Are Production Externalities?

Production externality refers to a side effect from an industrial operation, such as a paper mill producing waste that is dumped into a river. Production [externalities](https://www.investopedia.com/terms/e/externality.asp) are usually unintended, and their impacts are typically unrelated to and unsolicited by anyone. They can have economic, social, or environmental [side effects](https://www.investopedia.com/terms/s/side-effect.asp).

Production externalities can be measured in terms of the difference between the actual cost of production of the good and the real cost of this production to society at large. The impact of production externalities can be positive or negative or a combination of both.

### Key Takeaways

-   Production externality refers to a side effect from an industrial operation, such as a chemical company leaking improperly stored chemicals into the water table.
-   Production externalities can be measured in terms of the difference between the actual cost of production of the good and the real cost to society at large.
-   The impact of production externalities can be positive or negative or a combination.
-   A positive production externality is the positive effect an activity imposes on an unrelated third party; a negative externality is the negative effect an activity imposes on the same. 

## Understanding Production Externalities

There are many examples of production externalities, such as pollution and depletion of natural resources.

A logging company can pay for the cost of a tree that they remove, but the cost of replacing an entire forest once it is gone is exponentially more than the sum of its lost trees. Freeway traffic jams and health problems that arise from breathing secondhand smoke are further examples of externalities in production. A notable example of a large ecosystem of negative production externality is the Flint water crisis in 2019.

The British economist A. C. Pigou was the first to call out production externalities as a systemic phenomenon. Pigou argued that in the presence of externalities, we do not achieve [Pareto](https://www.investopedia.com/terms/p/paretoprinciple.asp) optimality, even under [perfect competition](https://www.investopedia.com/terms/p/perfectcompetition.asp). If the externalities are present, the resulting social benefit or cost becomes a combination of private and external benefits or costs. 

### Examples of Positive Production Externalities

A positive production externality (also called "external benefit" or "external economy" or "beneficial externality") is the positive effect an activity imposes on an unrelated third party. Similar to a negative externality. 

Going back to the example of the farmer who keeps the bees for their honey. A side effect or externality associated with such activity is the pollination of surrounding crops by the bees. The value generated by the pollination may be more important than the actual value of the harvested honey.

-   The construction and operation of an airport will benefit local businesses because of the increased accessibility.
-   An industrial company providing first aid classes for employees to increase workplace safety. This may also save lives outside the factory.
-   A foreign firm that demonstrates up-to-date technologies to local firms and improves their productivity.

### Examples of Negative Production Externalities

Similarly, a negative production externality is the negative effect an activity imposes on an unrelated third party. 

-   Noise pollution produced by someone playing loud music in an apartment building results in sleep deprivation for their neighbor.
-   Increased usage of antibiotics propagates increased antibiotic-resistant infections.
-   The development of Ill-health, notably early-onset Type II diabetes, and metabolic syndrome, as a result of companies over-processing foods—primarily the removal of fiber and the addition of sugars.
