---
alias: [Unlevered Free Cash Flow (UFCF)]
created: 2021-03-03T00:25:51 (UTC +11:00)
tags: [Unlevered Free Cash Flow (UFCF), What Unlevered Free Cash Flow (UFCF) Reveals]
source: https://www.investopedia.com/terms/u/unlevered-free-cash-flow-ufcf.asp
author: Adam Hayes
---

# Unlevered Free Cash Flow (UFCF)

> ## Excerpt
> Unlevered free cash flow (UFCF) is a company's cash flow before interest payments are taken into account. UFCF can be reported in a company's financial statements or calculated using financial statements by analysts.

---

What Unlevered Free Cash Flow (UFCF) Reveals
## What Is Unlevered Free Cash Flow (UFCF)?

Unlevered free cash flow (UFCF) is a company's cash flow before taking interest payments into account. Unlevered free cash flow can be reported in a company's [financial statements](https://www.investopedia.com/terms/f/financial-statements.asp) or calculated using financial statements by analysts. Unlevered free cash flow shows how much cash is available to the firm before taking financial obligations into account.

## The Formula for UFCF is:

UFCF\=EBITDA−CAPEX−Working Capital−Taxeswhere:UFCF\=Unlevered free cash flow\\begin{aligned} &\\text{UFCF} = \\textit{EBITDA} - \\textit{CAPEX} - \\text{Working Capital} - \\text{Taxes} \\\\ &\\textbf{where:} \\\\ &\\text{UFCF} = \\text{Unlevered free cash flow} \\\\ \\end{aligned}

The formula for unlevered free cash flow uses [earnings before interest, taxes, depreciation and amortization](https://www.investopedia.com/terms/e/ebitda.asp) (EBITDA) and [capital expenditures](https://www.investopedia.com/terms/c/capitalexpenditure.asp) (CAPEX), which represents the investments in buildings, machines and equipment. It also uses working capital, which includes inventory, accounts receivable and accounts payable.

## What Does Unlevered Free Cash Flow Reveal?

Unlevered free cash flow is the gross free cash flow generated by a company. Leverage is another name for debt, and if cash flows are levered, that means they are net of interest payments. Unlevered free cash flow is the free cash flow available to pay all stakeholders in a firm, including debt holders as well as equity holders.

[Like levered free cash flow](https://www.investopedia.com/ask/answers/111714/whats-difference-between-levered-and-unlevered-free-cash-flow.asp), unlevered free cash flow is net of capital expenditures and working capital needs – the cash needed to maintain and grow the company's asset base in order to generate revenue and earnings. Non-cash expenses such as depreciation and amortization are added back to earnings to arrive at the firm's unlevered free cash flow.

A company that has a large amount of outstanding debt, being highly leveraged, is more likely to report unlevered free cash flow because it provides a rosier picture of the company's financial health. The figure shows how assets are performing in a vacuum because it ignores the payments made for debt incurred to obtain those assets. Investors have to make sure to consider debt obligations since highly leveraged companies are at greater risk for bankruptcy.

### Key Takeaways

-   Unlevered free cash flow (UFCF) shows how much cash is available to the firm before taking financial obligations into account.
-   UFCF is of interest to investors because it indicates how much cash a business has to expand.
-   UFCF can be contrasted with levered free cash flow which does take into account financial obligations.

## The Difference Between Levered and Unlevered Free Cash Flow

The difference between levered and unlevered free cash flow is the inclusion of expenses. [Levered cash flow](https://www.investopedia.com/terms/l/levered-free-cash-flow.asp) is the amount of cash a business has after it has met all of its financial obligations, such as interest, loan payments and [operating expenses](https://www.investopedia.com/terms/o/operating_expense.asp). Unlevered free cash flow is the money the business has _before_ paying those financial obligations. Financial obligations will be paid from levered free cash flow.

The difference between the levered and unlevered cash flow is also an important indicator. The difference shows how many financial obligations the business has and if the business is overextended or operating with a healthy amount of debt. It is possible for a business to have a negative levered cash flow if its expenses are more than what the company earned. This is not an ideal situation, but as long as it's a temporary issue, investors should not be too rattled.

## Limitations of Unlevered Free Cash Flow

Companies looking to demonstrate better numbers can manipulate unlevered free cash flow by laying off workers, delaying capital projects, liquidating inventory or delaying payments to suppliers. All of these actions have consequences, and investors should discern whether improvements in unlevered free cash flow are transitory or genuinely convey improvements in the underlying business of the company.

Unlevered free cash flow is computed before interest payments, so viewing it in a bubble ignores the capital structure of a firm. After accounting for interest payments, the levered free cash flow of a firm may actually be negative, a possible sign of negative implications down the road. Analysts should assess both unlevered and levered free cash flow over time for trends and not give too much weight to a single year.
