---
alias: [Batch Processing]
created: 2021-02-28T21:37:43 (UTC +11:00)
tags: [Batch Processing Definition, Batch Processing Explained]
source: https://www.investopedia.com/terms/b/batch-processing.asp
author: ByAdam Barone
---

# Batch Processing Definition

> ## Excerpt
> Batch processing is the processing transactions that are processed in a group or batch as opposed to individually. It applies to the computation of information or data.

---

Batch Processing Explained
## What Is Batch Processing?

Batch processing is the processing of [transactions](https://www.investopedia.com/terms/t/transaction.asp) in a group or batch. No user interaction is required once batch processing is underway. This differentiates batch processing from transaction processing, which involves processing transactions one at a time and requires user interaction.

While batch processing can be carried out at any time, it is particularly suited to end-of-cycle processing, such as for processing a bank's reports at the end of a day or generating monthly or biweekly [payrolls](https://www.investopedia.com/terms/p/payroll.asp).

### Key Takeaways

-   Batch processing is a technique for automating and processing multiple transactions as a single group.
-   Batch processing helps in handling tasks like payroll, end-of-month reconciliation, or settling trades overnight.
-   Batch processing systems can save money and labor over time, but they may be costly to design and implement up-front.

## Understanding Batch Processing

For large enterprises, batch processing became a normal way of data compilation, organization, and report generation around the middle of the 20th century with the introduction of the mainframe computer. The early mechanics of processing a batch involved feeding a computer a stack of punched cards that held commands, or directions, for the computer to follow.

Herman Hollerith (1860-1929) is credited with developing the punch card around 1890 when he was employed as a statistician for the U.S. Census Bureau. It was this punch card that became the seed for widespread batch processing around 50 years later.

Batch processing jobs are run on regularly scheduled times (e.g., overnight) or on an as-needed basis. As an example, bills for [utilities](https://www.investopedia.com/terms/u/utility.asp) and other services received by consumers are typically generated by batch processing each month. Batch processing is beneficial because it is a cost-effective means of handling large amounts of data at once. One caveat is that the inputs for the processing must be correct or else the results of the whole batch will be faulty, which would cost time and money.

## History of Batch Processing

A defining characteristic of batch processing is a lack of human intervention, with few, if any, manual processes to kick it off. This is part of what makes it so efficient in modern times, but it wasn't always that way.

Batch processing started with punch cards, which were tabulated into instructions for computers. Entire decks, or batches, of cards, would be processed at one time. This system, created by Herman Hollerith, goes as far back as 1890. Hollerith developed it to be used to process data from the U.S. Census. Punched manually, the card was fed into and ready by an electromechanical device. Hollerith patented his invention as the "Electronic Tabulating Machine", and later joined a group of other inventors and investors to form the Computing-Tabulating-Recording Company (CTR), which would eventually become IBM.

Batch processing started with the use of punch cards.

Unlike earlier iterations, the functions of modern batch processing are completely automated to meet certain conditions of time. While some tasks are done immediately, others are conducted in real-time. The latter are monitored on a regular basis. If there are any problems with the process, the system notifies the appropriate personnel through exception-based management alerts. This saves [managers](https://www.investopedia.com/articles/financial-theory/10/manage-business-like-jack-welch.asp) time for their daily duties and other pressing tasks without having to supervise the batch processing system.

The software identifies exceptions through a system of monitors and dependencies, which causes the batch processing to start. Exceptions may include online customer orders or a request from the system for new supplies.

Because batch processing involves handling large amounts of data at once, if the inputs are off in some way, the whole batch will be flawed, wasting time and money.

## Advantages of Batch Processing

### Faster and Lower Cost

[Operational costs](https://www.investopedia.com/terms/o/operating-cost.asp) such as labor and equipment are cut when batch processing is used. This is because it eliminates the need for human clerks and physical hardware like computers. And because batch processing is designed to be quick and efficient, and to cut out human error, key personnel can focus their efforts on their daily duties.

### Offline Features

Unlike others, batch processing systems work anywhere, any time. That means they continue to work outside regular business hours. They can also work in the background in an offline setting, so even during down periods, you can rest assured they'll still work without putting a dent in the organization's daily routine.

### Hands-Off Approach

As mentioned above, having a batch processing system in place gives managers and other key personnel time to do their own jobs without having to spend time supervising batches. Alerts are sent if there are ever any problems. This allows the manager to take a hands-off approach to batch processing.

## Disadvantages of Batch Processing

Business owners may want to consider a few of the pitfalls of batch processing before putting such a system into place.

### Deployment and Training

Like many technologies, a degree of training is required to manage batch processing systems. Managers will need to learn what triggers a batch, how to schedule them, and what exception notifications mean, among other things.

### Debugging

Someone within the company or organization should be familiar with the system. That's because they're often very complex. Without a knowledgeable person on the team, you may need to hire someone else to help you out.

### Cost

Batch processing infrastructure can be an expensive capital outlay. For some businesses, the costs may seem unfeasible.
