---
alias: [Demand For Labor]
created: 2021-03-02T19:15:54 (UTC +11:00)
tags: [Demand For Labor, Demand For Labor]
source: https://www.investopedia.com/terms/d/demand_for_labor.asp
author: [[Will]] Kenton
---

# [[Demand For Labor]]

> ## Excerpt
> The [[Demand For Labor|demand for labor]] describes the amount and market wage rate workers and employers settle upon at any given moment.

---

[[Demand For Labor]]
## What is [[Demand For Labor|Demand for Labor]]

When producing goods and services, businesses require labor and capital as inputs to their production process. The [[Demand For Labor|demand for labor]] is an [[economics principle]](https://www.investopedia.com/terms/e/economicgrowth.asp) derived from the demand for a firm's output. That is, if demand for a firm's output increases, the firm [[Will|will]] demand more labor, thus hiring more staff. And if demand for the firm's output of goods and services decreases, in turn, it will require less labor and its demand for labor will fall, and less staff will be retained.

[[Labor Market|Labor market]] factors drive the [[Supply|supply]] and [[Demand For Labor|demand for labor]]. Those seeking employment [[Will|will]] supply their labor in exchange for wages. Businesses demanding labor from workers will pay for their time and skills.

## BREAKING DOWN [[Demand For Labor|Demand for Labor]]

[[Demand For Labor|Demand for labor]] is a concept that describes the amount of demand for labor that an economy or firm is willing to employ at a given point in time. This demand may not necessarily be in long-run [[equilibrium]](https://www.investopedia.com/terms/e/equilibrium.asp). It is determined by the real wage firms are willing to pay for this labor and the number of workers willing to [[Supply|supply]] labor at that wage.

A profit-maximizing entity [[Will|will]] command additional units of labor according to the marginal decision rule: If the extra output that is produced by hiring one more unit of labor adds more to total revenue than it adds to the total cost, the firm will increase profit by increasing its use of labor. It will continue to hire more and more labor up to the point that the extra revenue generated by the additional labor no longer exceeds the extra cost of the labor. This relationship is also called the marginal product of labor (MPL) in the [[Economics|economics]] community.

## Other Considerations in [[Demand For Labor|Demand for Labor]]

According to the [[law of diminishing marginal returns]](https://www.investopedia.com/terms/l/lawofdiminishingmarginalreturn.asp), by definition, in most sectors, eventually the MPL [[Will|will]] decrease. Based on this law: as units of one input are added (with all other inputs held constant) a point will be reached where the resulting additions to output will begin to decrease; that is marginal product will decline.

Another consideration is the [[marginal revenue product of labor (MRPL)]](https://www.investopedia.com/terms/m/marginal-revenue-product-mrp.asp), which is the change in revenue that results from employing an additional unit of labor, holding all other inputs constant. This can be used to determine the optimal number of workers to employ at a given market wage rate. According to economic theory, profit-maximizing firms [[Will|will]] hire workers up to the point where the marginal revenue product is equal to the wage rate because it is not efficient for a firm to pay its workers more than it will earn in revenues from their labor.

## Common Reasons for a Shift in Labor Demand

-   Changes in the marginal [[Productivity|productivity]] of labor, such as technological advances brought on by computers
-   Changes in the prices of other factors of production, including shifts in the relative prices of labor and capital [[Stock|stock]]
-   Changes in the price of an entity’s output, usually from an entity charging more for their product or service
