---
alias: [Gross Income Multiplier]
created: 2021-03-02T20:27:49 (UTC +11:00)
tags: [Gross Income Multiplier Definition, [[Gross Income]] Multiplier]
source: https://www.investopedia.com/terms/g/gross-income-multiplier.asp
author: [[Will]] Kenton
---

# [[Gross Income Multiplier]] Definition

> ## Excerpt
> The [[Gross Income Multiplier|gross income multiplier]] is obtained by dividing the property's sale price by its gross annual rental income, and is used in valuing commercial real estates, such as shopping centers and apartment complexes.

---

[[Gross Income Multiplier]]
## What Is a [[Gross Income Multiplier]]?

A [[Gross Income Multiplier|gross income multiplier]] (GIM) is a rough measure of the value of an investment property. It is calculated by dividing the property's sale price by its gross annual rental income. Investors can use the GIM—along with other methods like the [[capitalization rate]](https://www.investopedia.com/terms/c/capitalizationrate.asp) (cap rate) and [[discounted cash flow]](https://www.investopedia.com/terms/d/dcf.asp) method—to value [[commercial real estate]](https://www.investopedia.com/terms/c/commercialrealestate.asp) properties like shopping centers and apartment complexes.

### Key Takeaways

-   A [[Gross Income Multiplier|gross income multiplier]] is a rough measure of the value of an investment property.
-   GIM is calculated by dividing the property's sale price by its gross annual rental income.
-   Investors shouldn't use the GIM as the sole valuation metric because it doesn't take an income property's operating costs into account.

## Understanding the [[Gross Income Multiplier]]

Valuing an investment property is important for any investor before signing the real [[Estate|estate]] contract. But unlike other investments—like [[stocks]](https://www.investopedia.com/terms/s/[[Stock|stock]].asp)—there's no easy way to do it. Many professional real estate investors believe the income generated by a property is much more important than its [[appreciation]](https://www.investopedia.com/terms/a/appreciation.asp).

The [[Gross Income Multiplier|gross income multiplier]] is a [[metric]](https://www.investopedia.com/terms/m/metrics.asp) widely used in the real [[Estate|estate]] industry. It can be used by investors and real estate professionals to make a rough determination whether a property's asking price is a good deal—just like the [[price-to-earnings]](https://www.investopedia.com/terms/p/price-earningsratio.asp) (P/E) ratio can be used to value companies in the [[Stock|stock]] market.

Multiplying the GIM by the property's gross annual [[income]](https://www.investopedia.com/terms/i/income.asp) yields the property's value or the price for which it should be sold. A low [[Gross Income Multiplier|gross income multiplier]] means that a property may be a more attractive investment because the [[Gross Income|gross income]] it generates is much higher than its market value.

## Special Considerations

A [[Gross Income Multiplier|gross income multiplier]] is a good general real [[Estate|estate]] metric. But there are limitations because it doesn't take various factors into account including a property's [[operating costs]](https://www.investopedia.com/terms/o/operating-cost.asp) including utilities, taxes, maintenance, and vacancies. For the same reason, investors shouldn't use the GIM as a way to compare a potential investment property to another, similar one. In order to make a more accurate comparison between two or more properties, investors should use the net income multiplier (NIM). The NIM factors in both the income and the operating expenses of each property.

Use the net income multiplier to compare two or more properties.

## Drawbacks of the [[Gross Income Multiplier]] Method

The GIM is a great starting point for investors to value prospective [[real estate]](https://www.investopedia.com/terms/r/realestate.asp) investments. That's because it's easy to calculate and provides a rough picture of what purchasing the property can mean to a buyer. The [[Gross Income Multiplier|gross income multiplier]] is hardly a practical valuation model, but it does [[Offer|offer]] a back of the envelope starting point. But, as mentioned above, there are limitations and several key drawbacks to consider when using this figure as a way to value investment properties.

A natural argument against the multiplier method arises because it’s a rather crude valuation technique. Because changes in [[interest rates]](https://www.investopedia.com/terms/i/interestrate.asp)—which affect discount rates in the time value of money calculations—sources, [[revenue]](https://www.investopedia.com/terms/r/revenue.asp), and expenses are not explicitly considered.

Other drawbacks include:

-   The GIM method assumes uniformity in properties across similar classes. Practitioners know from experience that [[expense ratios]](https://www.investopedia.com/terms/e/expenseratio.asp) among similar properties often differ as a result of such factors as deferred maintenance, property age and the quality of property manager.
-   The GIM estimates value based on [[Gross Income|gross income]] and not [[net operating income]](https://www.investopedia.com/terms/n/noi.asp) (NOI), while a property is purchased based primarily on its net earning power. It is entirely possible that two properties can have the same NOI even though their gross incomes differ significantly. Thus, the GIM method can easily be misused by those who don’t appreciate its limits.
-   A GIM fails to account for the remaining economic life of comparable properties. By ignoring remaining economic life, a practitioner can assign equal values to a new property and a 50-year-old property—assuming they generate equal incomes.

## Example of [[Gross Income Multiplier]] Calculation

A property under review has an effective [[Gross Income|gross income]] of $50,000. A comparable sale is available with an effective income of $56,000 and a selling value of $392,000 (in reality, we’d seek a number of comparable to improve analysis).

Our GIM would be $392,000 ÷ $56,000 = 7.

This comparable—or [[comp]](https://www.investopedia.com/terms/c/comps.asp) as is it often called in practice—sold for seven times (7x) its effective gross. Using this multiplier, we see this property has a capital value of $350,000. This is found using the following formula:

V = GIM x EGI

7 x $50,000 = $350,000.
