---
alias: [Operating [[Cash Flow]] Demand, OCFD]
created: 2021-03-02T22:22:12 (UTC +11:00)
tags: [Operating Cash Flow Demand (OCFD), Operating Cash Flow Demand (OCFD)]
source: https://www.investopedia.com/terms/o/ocfd.asp
author: [[Will]] Kenton
---

# [[Operating Cash Flow Demand (OCFD)]]

> ## Excerpt
> Operating [[Cash Flow|cash flow]] demand is a measure of the amount of operating cash flow needed to meet the capital costs of a company's strategic investments.

---

[[Operating Cash Flow Demand (OCFD)]]
## What Does Operating [[Cash Flow]] Demand Mean?

[[Operating Cash Flow Demand (OCFD)|Operating cash flow demand (OCFD)]] is a measure of the amount of operating [[Cash Flow|cash flow]] needed to meet the capital costs of a company's strategic investments. This value is used to compute the cash value added of a company's strategic investments and operations.

## Understanding [[Operating Cash Flow Demand (OCFD)]]

A strategic investment is any investment in a game plan. The [[Operating Cash Flow Demand (OCFD)|operating cash flow demand (OCFD)]] is the amount of [[cash flow]](https://www.investopedia.com/terms/c/cashflow.asp) needed for each strategic investment to have a net present value of zero, or achieve minimum profitability. For example, if a company's strategic investment is the purchase of a plant in a new market, the OCFD would be the minimum amount of cash that the plant would need to generate over its life to meet the [[Return|return]] required by investors.

## Australian Company GUD [[Holdings]] and OFCD

Australian company, GUD [[Holdings]], is the corporate parent for several household brands, such as Ryco filters, Sunbeam, Davey Pumps and Lock Focus. After Ian Campbell took over as CEO of the company in 1998, he led a successful round and [[helped to make it a profitable enterprise]](https://www.smartcompany.com.au/[[Finance|finance]]/economy/how-to-rescue-a-company-on-the-ropes-the-gud-story/). A key to the company's financial strategy is that GUD managers are expected to generate strong financial numbers for a key performance indicator: [[cash value added]](https://www.investopedia.com/terms/c/cva.asp) (CVA) and that benchmark is related to OCFD. Cash value added (CVA) is a measure of a company's ability to generate [[Cash Flow|cash flow]] in excess of investors' required cash flow [[Return|return]] on investments by the company.

Campbell expects every GUD business to exceed 10% [[Weighted|weighted]] average [[Cost of Capital|cost of capital]] (the rate that a company is expected to pay, on average, to all its [[Security|security]] holders to [[Finance|finance]] its assets). GUD's businesses are judged on the growth in the cash value added compared to the prior year. (CVA is the amount of cash generated by a company through its operations. It is calculated by subtracting the operating [[Cash Flow|cash flow]] demand from the operating cash flow from the [[Cash Flow Statement|cash flow statement]].) Every year, Campbell sets a budget for each division and the weighted average cost of capital can vary from business to business. If, for example, it is set at 17% and the business achieves 18%, the managers [[Will|will]] receive bonuses. However, managers will not receive a bonus if the business comes in at 16%.
