---
alias: [Producer Surplus]
created: 2021-03-02T22:52:19 (UTC +11:00)
tags: [Producer [[Surplus]] Definition, Producer Surplus Definition]
source: https://www.investopedia.com/terms/p/producer_surplus.asp
author: Investopedia Staff
---

# [[Producer Surplus Definition]]

> ## Excerpt
> A producer [[Surplus|surplus]] is the difference between the amount of a good the producer is willing to accept for a product versus how much he actually receives in the transaction.

---

[[Producer Surplus Definition]]
## What Is a Producer [[Surplus]]?

Producer [[Surplus|surplus]] is the difference between how much a person would be willing to accept for given quantity of a good versus how much they can receive by selling the good at the market price. The difference or surplus amount is the benefit the producer receives for selling the good in the market. A producer surplus is generated by market prices in excess of the lowest price producers would otherwise be willing to accept for their goods. This may relate to [[Walras' law]](https://www.investopedia.com/terms/w/walras-law.asp).

### Key Takeaways

-   Producer [[Surplus|surplus]] is the total amount that a producer benefits from producing and selling a quantity of a good at the market price.
-   The total revenue that a producer receives from selling their goods minus the total cost of production equals the producer [[Surplus|surplus]].
-   Producer [[Surplus|surplus]] plus consumer surplus represents the total benefit to everyone in the market from participating in production and trade of the good.

## Understanding Producer [[Surplus]]

A producer [[Surplus|surplus]] is shown graphically below as the area above the producer's [[supply curve]](https://www.investopedia.com/terms/s/[[Supply|supply]]-curve.asp) that it receives at the price point (P(i)), forming a triangular area on the graph. The producer’s sales revenue from selling Q(i) units of the good is represented as the area of the rectangle formed by the axes and the red lines, and is equal to the product of Q(i) times the price of each unit, P(i).

Because the [[Supply|supply]] curve represents the marginal cost of producing each unit of the good, the producer’s total cost of producing Q(i) units of the good is the sum of the marginal cost of each unit from 0 to Q(i) and is represented by the area of triangle under the supply curve from 0 to Q(i). Subtracting the producer’s total cost (the triangle under the supply curve) from his total revenue (the rectangle) shows the producer’s total benefit (or producer [[Surplus|surplus]]) as the area of the triangle between P(i) and the supply curve.

Total revenue - total cost = producer [[Surplus|surplus]].

The size of the producer [[Surplus|surplus]] and its triangular depiction on the graph increases as the [[market price]](https://www.investopedia.com/terms/m/market-price.asp) for the good increases, and decreases as the market price for the good decreases.

Image by Julie Bang © Investopedia 2019

Producers would not sell products if they could not get at least the marginal cost to produce those products. The [[Supply|supply]] curve as depicted in the graph above represents the [[marginal cost curve]](https://www.investopedia.com/terms/m/marginalcostofproduction.asp) for the producer.

From an [[Economics|economics]] standpoint, [[marginal cost]](https://www.investopedia.com/ask/answers/051815/what-difference-between-marginal-benefit-and-marginal-cost.asp) includes opportunity cost. In essence, an opportunity cost is a cost of not doing something different, such as producing a separate item. The producer [[Surplus|surplus]] is the difference between the price received for a product and the marginal cost to produce it.

Because marginal cost is low for the first units of the good produced, the producer gains the most from producing these units to sell at the market price. Each additional unit costs more to produce because more and more resources must be withdrawn from alternative uses, so the marginal cost increases and the net producer [[Surplus|surplus]] for each additional unit is lower and lower.

## Consumer [[Surplus]] and Producer Surplus

A producer [[Surplus|surplus]] combined with a [[consumer surplus]](https://www.investopedia.com/terms/c/consumer_surplus.asp) equals overall economic surplus or the benefit provided by producers and consumers interacting in [[a free market]](https://www.investopedia.com/video/play/free-market-economy/) as opposed to one with [[Price Controls|price controls]] or quotas. If a producer could [[price discriminate]](https://www.investopedia.com/terms/p/price_discrimination.asp) correctly, or charge every consumer the maximum price the consumer is willing to pay, then the producer could capture the entire economic surplus. In other words, producer surplus would equal overall economic surplus.

However, the existence of producer [[Surplus|surplus]] does not mean there is an absence of a consumer surplus. The idea behind a [[free market]](https://www.investopedia.com/terms/f/freemarket.asp) that sets a price for a good is that both consumers and producers can benefit, with consumer surplus and producer surplus generating greater overall economic welfare. Market prices can change materially due to consumers, producers, a combination of the two or other outside forces. As a result, profits and producer surplus may change materially due to market prices.
