---
alias: [Risk-Adjusted [[Return]] On Capital, RAROC]
created: 2021-03-02T23:23:35 (UTC +11:00)
tags: [Risk-Adjusted Return On Capital (RAROC), [[Risk]]-Adjusted Return On Capital (RAROC) Definition]
source: https://www.investopedia.com/terms/r/raroc.asp
author: James Chen
---

# [[Risk]]-Adjusted [[Return]] On Capital (RAROC)

> ## Excerpt
> [[Risk]]-adjusted [[Return|return]] on capital (RAROC) is a modification to the standard return on an investment that accounts for the element of risk.

---

[[Risk-Adjusted Return On Capital (RAROC) Definition]]
## What Is [[Risk]]-Adjusted [[Return]] On Capital (RAROC)?

[[Risk]]-adjusted [[Return|return]] on capital ([RAROC](https://www.investopedia.com/terms/r/riskadjustedreturn.asp)) is a modified return on investment (ROI) figure that takes elements of risk into account. In [[financial analysis]](https://www.investopedia.com/terms/f/financial-analysis.asp), projects and investments with greater risk levels must be evaluated differently; RAROC thus accounts for changes in an investment’s profile by [[discounting]](https://www.investopedia.com/terms/d/discounting.asp) risky cash flows against less-risky cash flows.

### Key Takeaways

-   [[Risk]]-adjusted [[Return|return]] on capital (RAROC) is a risk-adjusted measure of the return on investment.
-   It does this by accounting for any expected losses and income generated by capital, with the assumption that riskier projects should be accompanied by higher expected returns
-   RAROC is most often used by banks and other financial sector companies.

## The Formula For RAROC Is

RAROC\=r−e−el+ifccwhere:RAROC\=[[Risk]]-adjusted [[Return|return]] on capitalr\=Revenuee\=Expensesel\=Expected loss which equals average lossel\=expected over a specified period of timeifc\=Income from capital which equalsifc\=(capital charges)×(the risk-free rate)c\=Capital\\begin{aligned}&RAROC=\\frac{r-e-el+ifc}{c}\\\\&\\textbf{where:}\\\\&\\text{RAROC}=\\text{Risk-adjusted return on capital}\\\\&r=\\text{Revenue}\\\\&e=\\text{Expenses}\\\\&el=\\text{Expected loss which equals average loss}\\\\&\\phantom{el=}\\text{expected over a specified period of time}\\\\&ifc=\\text{Income from capital which equals}\\\\&\\phantom{ifc=}\\text{(capital charges)}\\times{\\text{(the risk-free rate)}}\\\\&c=\\text{Capital}\\end{aligned}

## Understanding [[Risk]]-Adjusted [[Return]] On Capital

[[Risk]]-adjusted [[Return|return]] on capital is a useful tool in assessing potential acquisitions. The general [[Underlying|underlying]] assumption of RAROC is investments or projects with higher levels of risk [[Offer|offer]] substantially higher returns. Companies that need to compare two or more different projects or investments must keep this in mind.

## RAROC and Bankers Trust

RAROC is also referred to as a profitability-measurement framework, based on [[Risk|risk]], that allows analysts to examine a company’s financial performance and establish a steady view of profitability across business sectors and industries.

The RAROC metric was developed during the late 1970s by Bankers Trust, more specifically Dan Borge, its [[Principal|principal]] designer. The tool grew in popularity through the 1980s, serving as a newly developed adjustment to simple [[Return|return]] on capital (ROC). A commercial bank at the time, Bankers Trust adopted a business model similar to that of an investment bank. Bankers Trust had unloaded its retail lending and deposit businesses and dealt actively in exempt securities, with a [[Derivative|derivative]] business beginning to take root.

These wholesale activities facilitated the development of the RAROC model. Nationwide publicity led a number of other banks to develop their own RAROC systems. The banks gave their systems different names, essentially lingo used to indicate the same type of metric. Other methods include [[Return|return]] on [[Risk|risk]]-adjusted capital (RORAC) and risk-adjusted return on risk-adjusted capital (RARORAC). The most commonly used is still RAROC. Non-banking firms utilize RAROC as a metric for the effect that operational, market and credit risk have on finances.

## [[Return]] on [[Risk]]-Adjusted Capital

Not to be confused with RAROC, the [[Return|return]] on [[Risk|risk]]-adjusted capital ([RORAC](https://www.investopedia.com/terms/r/rorac.asp)) is used in financial analysis to calculate a rate of return, where projects and investments with higher levels of risk are evaluated based on the amount of capital at risk. More and more, companies are using RORAC as a greater amount of emphasis is placed on [[risk management]](https://www.investopedia.com/terms/r/riskmanagement.asp) throughout a company. The calculation for this metric is similar to RAROC, with the major difference being capital is adjusted for risk with RAROC instead of the rate of return.
