---
alias: [Total Shareholder [[Return]], TSR]
created: 2021-03-03T00:04:43 (UTC +11:00)
tags: [Total Shareholder [[Return]] (TSR) Definition, Total Shareholder Return (TSR) Definition]
source: https://www.investopedia.com/terms/t/tsr.asp
author: Akhilesh Ganti
---

# [[Total Shareholder Return (TSR) Definition]]

> ## Excerpt
> Total Shareholder [[Return]] factors in capital gains and dividends when measuring the total return generated by a [[Stock|stock]] to an investor.

---

[[Total Shareholder Return (TSR) Definition]]
## What is Total Shareholder [[Return]] (TSR)?

Total Shareholder [[Return]] (TSR) factors in [[capital gains]](https://www.investopedia.com/terms/c/capitalgain.asp) and [[dividends]](https://www.investopedia.com/terms/d/dividend.asp) when measuring the total return generated by a [[Stock|stock]] to an investor. TSR is the [[internal rate of return]](https://www.investopedia.com/terms/i/irr.asp) (IRR) of all cash flows to an investor during the [[holding period]](https://www.investopedia.com/terms/h/holdingperiod.asp) of an investment. Whichever way it is calculated, TSR means the same thing: the total amount returned to investors.

## Understanding Total Shareholder [[Return]] (TSR)

There are two basic ways that an Investor makes money in [[Stocks|stocks]] - capital gains and current income. A capital [[Gain|gain]] is the change in market price of the [[Stock|stock]] from the time it was purchased to the date it was sold (or the current price if it is still owned). Current income is the dividends paid out by the company from its earnings while the investor still owns the stock.

When calculating TSR, an investor must account for _only_ the dividends received during the period of [[Stock|stock]] ownership. For example, he may own the stock on the day the [[dividend]](https://www.investopedia.com/terms/d/dividend.asp) is payable, yet he receives the dividend only if he owned the stock on the ex-dividend day. Therefore, an investor needs to know the stock’s ex-dividend date rather than the dividend payment date when calculating TSR. Dividends paid include cash payments returned to stockholders, [[stock buyback]](https://www.investopedia.com/articles/02/041702.asp) programs, one-time dividend payments, and regular dividend payouts.

Total shareholder [[Return|return]] is the financial [[Gain|gain]] that results from a change in the [[Stock|stock]]'s price plus any dividends paid by the company during the measured interval divided by the initial [[Purchase Price|purchase price]] of the stock. Assume that an investor bought 100 [[Shares|shares]] at $20 and still owns the stock. Company paid out $4.50 in dividends since the investor bought the stock and the current price is $24.

**TSR = { (current price - [[Purchase Price|purchase price]]) + dividends } ÷ purchase price**

**TSR = { ($24 - $20) + $4.50 } ÷ $20 = 0.425 \* 100 = 42.5%**

TSR is most useful when measured over time as it shows the [[Long Term|long term]] value, the most accurate metric for gauging success, that was created by the company.

### Key Takeaways

-   There are two basic ways that an Investor makes money in [[Stocks|stocks]] - capital gains and current income (dividends).
-   Total Shareholder [[Return]] factors in capital gains and dividends when measuring the total return generated by a [[Stock|stock]] to an investor.
-   TSR represents an easily understood figure of the overall financial benefits generated for stockholders.

## Pros and Cons of Total Shareholder [[Return]]

TSR is best used when analyzing [[venture capital]](https://www.investopedia.com/terms/v/venturecapital.asp) and private [[Equity|equity]] investments. These investments typically involve multiple cash investments over the life of the business and single cash outflow at the end through [[an initial public offering]](https://www.investopedia.com/ask/answers/012015/what-difference-between-ipo-and-seasoned-issue.asp) (IPO) or sale.

Because TSR is expressed as a percentage, the figure is readily comparable with industry benchmarks or companies in the same sector. However, it reflects the past overall [[Return|return]] to shareholders without consideration of future returns.

TSR represents an easily understood figure of the overall financial benefits generated for stockholders. The figure measures how the market evaluates the overall performance of a company over a specific time period. However, TSR is calculated for publicly traded companies at the overall level, not at a divisional level. Also, TSR works only for investments with one or more cash inflows after purchase. In addition, TSR is externally focused and reflects the market’s perception of performance; therefore, TSR could be adversely affected if a fundamentally strong company’s share price suffers greatly in the [[short term]](https://www.investopedia.com/terms/s/shortterm.asp).

TSR does not measure the absolute size of an investment or its [[Return|return]]. For this reason, TSR may favor investments with high rates of return even when the dollar amount of the return is small. For example, a $1 investment returning $3 has a higher TSR than a $1 million investment returning $2 million. Also, TSR cannot be used when the investment generates interim cash flows. In addition, TSR does not take into consideration [[Cost of Capital|cost of capital]] and cannot compare investments over different time periods.
