---
alias: [Unrelated Business [[Taxable Income]], UBTI]
created: 2021-03-03T00:25:52 (UTC +11:00)
tags: [Unrelated Business [[Taxable Income]] (UBTI), Unrelated Business Taxable Income (UBTI)]
source: https://www.investopedia.com/terms/u/ubti.asp
author: Julia Kagan
---

# [[Unrelated Business Taxable Income (UBTI)]]

> ## Excerpt
> [[Unrelated Business Taxable Income (UBTI)|Unrelated business taxable income (UBTI)]] is income regularly generated by a tax-exempt entity by means of taxable activities.

---

[[Unrelated Business Taxable Income (UBTI)]]
## What Does Unrelated Business [[Taxable Income]] Mean?

[[Unrelated Business Taxable Income (UBTI)|Unrelated business taxable income (UBTI)]] is income regularly generated by a tax-exempt entity by means of taxable activities. This income is not related to the main function of the entity but is needed to generate a small portion of income.1

As of April 23, 2020, the IRS has issued proposed guidance for calculating UBTI. The guidance gives taxpayers guidance to apply UBTI silo rules for tax exempt organizations.2

### Key Takeaways

-   [[Unrelated Business Taxable Income (UBTI)|Unrelated business taxable income (UBTI)]] is income regularly generated by a tax-exempt entity by means of taxable activities.
-   UBTI prevents or limits tax-exempt entities from engaging in businesses that are unrelated to their primary purposes.
-   Most forms of [[Passive Income|passive income]], such as dividends, interest income, and capital gains from the sale or exchange of capital assets, are not treated as UBTI.

## Understanding [[Unrelated Business Taxable Income (UBTI)]]

The [[Internal Revenue Code (IRC)]](https://www.investopedia.com/terms/i/internal-revenue-code.asp) [[Section 501]](https://www.investopedia.com/terms/1/501c.asp) grants tax-exempt status to a variety of tax-exempt and mutually beneficial organizations.3 However, an organization that is recognized as a tax-exempt entity, such as a nonprofit or educational organization, may be liable for tax if it engages in and derives income from unrelated business activity. The [[Internal Revenue Service (IRS)]](https://www.investopedia.com/terms/i/irs.asp) defines the income generated from unrelated business activities as income from a trade or business regularly carried on, that is not substantially related to the purpose that is the basis of the organization's exemption from tax.1

UBTI was introduced in 1950 to ensure that tax-exempt businesses competed fairly with taxable companies in profit-generating activities.4 Furthermore, UBTI prevents or limits tax-exempt entities from engaging in businesses that are unrelated to their primary purposes. Most forms of [[passive income]](https://www.investopedia.com/terms/p/passiveincome.asp), such as [[dividends]](https://www.investopedia.com/terms/d/dividend.asp), interest income, and [[capital gains]](https://www.investopedia.com/terms/c/capitalgain.asp) from the sale or exchange of capital assets, are not treated as UBTI.5 If an investor holds an [[Individual Retirement Arrangement (IRA)]](https://www.investopedia.com/terms/i/ira.asp) that simply invests in traditional equities, mutual funds, and ETFs, the UBTI rules [[Will|will]] most likely not apply. However, if the fund generates income which qualifies as UBTI, the fund may be subject to [[Taxation|taxation]]. For example, income from a restaurant business that flows into an IRA is considered taxable and subject to UBTI tax.

Some transactions that may be considered unrelated business activity include:

-   Buying and selling a significant number of real [[Estate|estate]] properties in a year
-   Conducting operations in businesses—such as restaurants, convenience stores, lodging inns, gas stations, etc.—that generate active income and are operated through a [[pass-through entity]](https://www.investopedia.com/terms/f/flow-through.asp), such as a limited [[Liability|liability]] company (LLC) or [[master limited partnership (MLP)]](https://www.investopedia.com/terms/m/mlp.asp)
-   Using [[margin]](https://www.investopedia.com/terms/m/margin.asp) on a [[Stock|stock]] purchase
-   Making multiple private loans within a given year

Income generated from eligible taxable activities are subject to an estimated tax of up to 37% on income over $12,750 (as of 2019).6 Form 990-W, "Estimated Tax on Unrelated Business [[Taxable Income]] for Tax-Exempt Organizations," is a worksheet provided by the IRS to determine the amount of estimated tax payments required. An exempt organization that has $1,000 or more of [[gross income]](https://www.investopedia.com/terms/g/grossincome.asp) from an unrelated business must file additional tax with the IRS through Form 990-T.7 An organization must pay estimated tax if it expects its tax for the year to be $500 or more.8
